### ISSUE TITLE
Broken migrations

### ISSUE THREAD

**Issue by sveredyuk** [pivorakmeetup/pivorak-web-app#501]
New app.
`rake db:create`
`rake db:migrate`

and fails:
`
== 20170714191645 SeedNotifyAdminAboutCanceledAttendee: migrating =============
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

unknown attribute 'note' for EmailTemplate.
/Users/svr/.rvm/gems/ruby-2.3.1/gems/activemodel-5.0.2/lib/active_model/attribute_assignment.rb:48:in `_assign_attribute'
/Users/svr/.rvm/gems/ruby-2.3.1/gems/activemodel-5.0.2/lib/active_model/attribute_assignment.rb:40:in `block in _assign_attributes'
/Users/svr/.rvm/gems/ruby-2.3.1/gems/activemodel-5.0.2/lib/active_model/attribute_assignment.rb:39:in `each'
/Users/svr/.rvm/gems/ruby-2.3.1/gems/activemodel-5.0.2/lib/active_model/attribute_assignment.rb:39:in `_assign_attributes'
/Users/svr/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.2/lib/active_record/attribute_assignment.rb:26:in `_assign_attributes'
/Users/svr/.rvm/gems/ruby-2.3.1/gems/activemodel-5.0.2/lib/active_model/attribute_assignment.rb:33:in `assign_attributes'
/Users/svr/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.2/lib/active_record/core.rb:319:in `initialize'
/Users/svr/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.2/lib/active_record/inheritance.rb:65:in `new'
/Users/svr/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.2/lib/active_record/inheritance.rb:65:in `new'
/Users/svr/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.2/lib/active_record/persistence.rb:50:in `create!'
/Users/svr/Documents/Projects/rails/pivorak-web-app/db/migrate/20170714191645_seed_notify_admin_about_canceled_attendee.rb:3:in `up'
/Users/svr/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.2/lib/active_record/migration.rb:792:in `exec_migration'
/Users/svr/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.2/lib/active_record/migration.rb:773:in `block (2 levels) in migrate'
/Users/svr/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.2/lib/active_record/migration.rb:772:in `block in migrate'
/Users/svr/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:398:in `with_connection'
`

**Comment by sveredyuk** [comment]
@avozniak  Still reproducing.

rake db:drop
rake db:create
rake db:migrate... boom!

**Comment by sveredyuk** [comment]
Sorry, my fault
